add_newline = false
line_break.disabled = false

aws.disabled = true
package.disabled = true
git_state.disabled = true

format = """
$cmd_duration\
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal\
$custom\
$line_break\
$lua\
$jobs\
$battery\
$time\
$status\
$shell\
$character"""

git_status.format = '([\($all_status$ahead_behind\)]($style)) ' 

cmake.format = '\[[$symbol($version)]($style)\]'
conda.format = '\[[$symbol$environment]($style)\]'
crystal.format = '\[[$symbol($version)]($style)\]'
dart.format = '\[[$symbol($version)]($style)\]'
deno.format = '\[[$symbol($version)]($style)\]'
docker_context.format = '\[[$symbol$context]($style)\]'
dotnet.format = '\[[$symbol($version)(🎯 $tfm)]($style)\]'
elm.format = '\[[$symbol($version)]($style)\]'
erlang.format = '\[[$symbol($version)]($style)\]'
gcloud.format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'
golang.format = '\[[$symbol($version)]($style)\]'
helm.format = '\[[$symbol($version)]($style)\]'
hg_branch.format = '\[[$symbol$branch]($style)\]'
julia.format = '\[[$symbol($version)]($style)\]'
kotlin.format = '\[[$symbol($version)]($style)\]'
kubernetes.format = '\[[$symbol$context( \($namespace\))]($style)\]'
lua.format = '\[[$symbol($version)]($style)\]'
nim.format = '\[[$symbol($version)]($style)\]'
nix_shell.format = '\[[$symbol$state( \($name\))]($style)\]'
nodejs.format = '\[[$symbol($version)]($style)\]'
ocaml.format = '\[[$symbol($version)(\($switch_indicator$switch_name\))]($style)\]'
openstack.format = '\[[$symbol$cloud(\($project\))]($style)\]'
perl.format = '\[[$symbol($version)]($style)\]'
php.format = '\[[$symbol($version)]($style)\]'
purescript.format = '\[[$symbol($version)]($style)\]'
red.format = '\[[$symbol($version)]($style)\]'
ruby.format = '\[[$symbol($version)]($style)\]'
scala.format = '\[[$symbol($version)]($style)\]'
swift.format = '\[[$symbol($version)]($style)\]'
terraform.format = '\[[$symbol$workspace]($style)\]'
time.format = '\[[$time]($style)\]'
vagrant.format = '\[[$symbol($version)]($style)\]'
vlang.format = '\[[$symbol($version)]($style)\]'
zig.format = '\[[$symbol($version)]($style)\]'

[cmd_duration]
format = "[$duration]($style) "
style = "blue"

[username]
style_user = "bold yellow"
format = '\[[$user]($style)@'
show_always = true
disabled = false

[hostname]
ssh_only = false
style = "bold yellow"
format = '[$hostname]($style)\]::'
trim_at = "."
disabled = false

[directory]
style = "bold cyan"
format= "[$path]($style)[$read_only]($read_only_style) "
home_symbol = "~"
read_only = " "

[git_branch]
format = "| [$symbol$branch]($style)"
symbol = " "

[elixir]
format = '\[[$symbol($version \(OTP $otp_version\))]($style)\]'
symbol = " "

[java]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[python]
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'
symbol = " "

[rust]
format = '\[[$symbol($version)]($style)\]'
symbol = " "
